### ISSUE TITLE
[REFACTOR] 리팩토링 할 예정인 기능

### ISSUE THREAD

**Issue by jaeyeong815** [Storage-with-chatGPT/cooking-wiki#10]
## Description

기능을 구현하면서 리팩토링 할 부분 발견하면 아래 todo에 추가하기

## To-Do

- [x] 로딩중 표시
- [x] 요리 추천 다시 받기 (새로고침 처럼)
- [x] 다른 요리 레시피 안내받기
- [x] 재료를 입력 안해도 등록되는 버그 수정하기
- [x] 헤더/내비게이션바 만들기
- [x] 요리 추천/레시피 안내 페이지에서 냉장고 페이지로 뒤로가기
- [x] 재료 많이 등록할 경우 스크롤
- [x] 재료 재선택 후 검색하면 이전 검색했던 레시피 뜨는 문제 수정하기
- [ ] 레시피 데이터 가공 로직 확인합시다,,
- [x] 현재 사용자에게 안내할 때 alert를 사용하고 있는데, 다른 방법으로 안내하도록 수정
- [x] 모바일 반응형
