### ISSUE TITLE
[FEAT] 디자인하기

### ISSUE THREAD

**Issue by jaeyeong815** [Storage-with-chatGPT/cooking-wiki#13]
## Description

디자인 입히기

## To-Do

- [x] 전체적인 디자인
- [x] 검색 결과 페이지 분리
- [x] 선택된 요리 표시하기
- [x] 레시피 안내 페이지 css
- [x] 전체적인 레이아웃
