### ISSUE TITLE
[FEAT] 서버 코드 작성

### ISSUE THREAD

**Issue by jaeyeong815** [Storage-with-chatGPT/cooking-wiki#19]
## Description

배포 시 API KEY가 노출되는 문제로 백엔드 코드 추가 작성

## To-Do

- [x] client, server 폴더 생성하여 파일 분리
- [x] server 코드 작성
- [x] 클라이언트에서 백 코드 연결
