### ISSUE TITLE
[FEAT] 마이 냉장고 레이아웃

### ISSUE THREAD

**Issue by jaeyeong815** [Storage-with-chatGPT/cooking-wiki#2]
## Description

마이 냉장고 페이지에 헤더 / 재료 선택 / 질문 버튼을 포함한 페이지를 구성
디자인은 아직 반영하지 않고, 대략적인 위치만 잡는 것을 목표로 함

## To-Do

- [x] 헤더: h1 태그, 마이 냉장고라는 타이틀 작성
- [x] 재료 선택: input 태그로 입력해서 값 받는 형태
- [x] 질문 버튼: button 태그
- [x] index.tsx에 구현되어있는 코드들 분리

## Memo

모바일 퍼스트로 구현할거여서 가운데 정렬 된 모양으로 구현하기
