### ISSUE TITLE
[FEAT] 마이 냉장고에서 검색할 재료 선택하는 기능

### ISSUE THREAD

**Issue by jaeyeong815** [Storage-with-chatGPT/cooking-wiki#4]
## Description

현재 냉장고에 있는 재료를 입력하는 것 까지 구현하였음.
입력한 재료들 중 한가지 이상 선택하여 질문을 해야하기 때문에,
재료를 선택하는 기능을 구현하려고 함

## To-Do

- [x] 상태 관리를 위한 RTK 설정
- [x] 한 컴포넌트에 구현되어 있는 로직 분리
- [x] 선택 기능 구현
