### ISSUE TITLE
[FEAT] 마이 냉장고 나머지 기능 구현

### ISSUE THREAD

**Issue by jaeyeong815** [Storage-with-chatGPT/cooking-wiki#7]
## Description

큰 기능은 대부분 구현 했고, 나머지 생각나는 기능들 추가해서 구현 할 예정

## To-Do

- [x] 등록한 재료 삭제하기
- [x] 선택한 재료 삭제하기
- [x] 선택한 재료로 검색하기
