### ISSUE TITLE
[FEAT] 추천받은 요리의 레시피 알려주기

### ISSUE THREAD

**Issue by jaeyeong815** [Storage-with-chatGPT/cooking-wiki#9]
## Description

가지고 있는 재료로 만들 수 있는 요리를 추천하는 기능까지 구현 하였고,
추천받은 요리 중 하나를 선택해 레시피를 답변 받을 수 있는 기능을 구현해야 함

## To-Do

- [x] 추천 받은 요리 리스트 전역 상태로 추가
- [x] 현재 1. ~ , 2~ 이렇게 번호랑 같이 상태에 저장되는데, 이름만 저장되도록 수정
- [x] 추천 받은 요리 중 한가지를 고를 수 있는 기능
- [x] 레시피 알려주는 openai 질문 기능 생성 (+ 현재 로직 분리)
- [x] 답변 받은 내용 상태관리
- [x] 선택 버튼과 질문 api 연결
